{{- if and .Values.enterprise.enabled .Values.enterprise.arena.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.enterprise.arena.worker.serviceAccount.name | default (printf "%s-arena-worker" (include "omnia.fullname" .)) }}
  labels:
    {{- include "omnia.labels" . | nindent 4 }}
    app.kubernetes.io/component: arena-worker
  {{- with .Values.enterprise.arena.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
