{{- if and .Values.license.key (not .Values.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: arena-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnia.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.license.key | b64enc | quote }}
{{- end }}
