{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnia.fullname" . }}-controller-manager
  labels:
    {{- include "omnia.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "omnia.selectorLabels" . | nindent 4 }}
{{- end }}
