---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-omnia-altairalabs-ai-v1alpha1-arenajob
  failurePolicy: Fail
  name: varenajob.kb.io
  rules:
  - apiGroups:
    - omnia.altairalabs.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - arenajobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-omnia-altairalabs-ai-v1alpha1-arenasource
  failurePolicy: Fail
  name: varenasource.kb.io
  rules:
  - apiGroups:
    - omnia.altairalabs.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - arenasources
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-omnia-altairalabs-ai-v1alpha1-arenatemplatesource
  failurePolicy: Fail
  name: varenatemplatesource.kb.io
  rules:
  - apiGroups:
    - omnia.altairalabs.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - arenatemplatesources
  sideEffects: None
