---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - omnia.altairalabs.ai
  resources:
  - agentruntimes
  - promptpacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omnia.altairalabs.ai
  resources:
  - agentruntimes/finalizers
  - promptpacks/finalizers
  verbs:
  - update
- apiGroups:
  - omnia.altairalabs.ai
  resources:
  - agentruntimes/status
  - promptpacks/status
  verbs:
  - get
  - patch
  - update
