## Append samples of your project ##
resources:
- omnia_v1alpha1_agentruntime.yaml
- omnia_v1alpha1_promptpack.yaml
- omnia_v1alpha1_toolregistry.yaml
- omnia_v1alpha1_provider.yaml
- omnia_v1alpha1_arenasource.yaml
- omnia_v1alpha1_arenaconfig.yaml
- omnia_v1alpha1_arenajob.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
