apiVersion: omnia.altairalabs.ai/v1alpha1
kind: ToolRegistry
metadata:
  labels:
    app.kubernetes.io/name: omnia
    app.kubernetes.io/managed-by: kustomize
  name: toolregistry-sample
spec:
  # TODO(user): Add fields here
