{{- if .Values.sessionApi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omnia.sessionApi.fullname" . }}
  labels:
    {{- include "omnia.sessionApi.labels" . | nindent 4 }}
  {{- with .Values.sessionApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
