{{- if .Values.sessionApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnia.sessionApi.fullname" . }}
  labels:
    {{- include "omnia.sessionApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sessionApi.service.type }}
  ports:
    - port: {{ .Values.sessionApi.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "omnia.sessionApi.selectorLabels" . | nindent 4 }}
{{- end }}
