{{- if and .Values.enterprise.enabled .Values.enterprise.evalWorker.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omnia.evalWorker.fullname" . }}
  labels:
    {{- include "omnia.evalWorker.labels" . | nindent 4 }}
{{- end }}
