{{- if .Values.demo.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.demo.namespace }}
  labels:
    app.kubernetes.io/name: omnia-demo
    app.kubernetes.io/part-of: {{ include "omnia.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
