apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arena-leader-election-rolebinding
  namespace: omnia-system
  labels:
    app.kubernetes.io/name: omnia-arena
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arena-leader-election-role
subjects:
- kind: ServiceAccount
  name: arena-controller-manager
  namespace: omnia-system
