apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arena-manager-rolebinding
  labels:
    app.kubernetes.io/name: omnia-arena
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arena-manager-role
subjects:
- kind: ServiceAccount
  name: arena-controller-manager
  namespace: omnia-system
