apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omnia-system

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: promptkit-lsp
  newName: ghcr.io/altairalabs/omnia/promptkit-lsp
  newTag: latest
